version: '3.5'

services:
  vertica1:
    image: jbfavre/vertica:latest     
    hostname: vertica1
    volumes:    
      - ./src/data:/etc/benchmark_data
      - ./vertica-cluster/vertica/files:/etc/vertica
    ports:
      - "33522:22"
      - "5433:5433"
      - "5444:5444"
  