version: '3.5'

services:
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./src/clickhouse/settings/node1:/etc/clickhouse-server
      - ./src/data:/etc/benchmark_data
      - ./src/clickhouse/settings/node1/init:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./src/clickhouse/settings/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./src/clickhouse/settings/node3/init:/docker-entrypoint-initdb.d
      - ./src/clickhouse/settings/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper      

  clickhouse-node4:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./src/clickhouse/settings/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper
