name: code-quality

on:
  push:
    branches: [ linter_check ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  wemake-python-styleguide flake8-html mypy lxml 

      - name: Create directories
        run: |
          mkdir -p reports/wemake-python-styleguide/
          mkdir -p reports/mypy/app/
          mkdir -p reports/mypy/etl/

      - name: Lint with wemake-python-styleguide
        run: |
          flake8 --exit-zero --format=html --htmldir=reports/wemake-python-styleguide/ 

      - name: Lint with mypy
        run: |
          mypy --html-report reports/mypy/app/ app
          mypy --html-report reports/mypy/etl/ etl

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports/