name: code-quality

on:
  push:
    branches: [ linter_check ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  wemake-python-styleguide flake8-html

      - name: Create directories
        run: |
          mkdir -p reports/wemake-python-styleguide/

      - name: Lint with wemake-python-styleguide
        run: |
          flake8 --exit-zero --format=html --htmldir=reports/wemake-python-styleguide/ 
